import React, { useState, useEffect, useCallback } from 'react';
import type { SerialPortInfo, DmxOutputMode } from '../../shared/types';
import { useSerialStore } from '../store/useSerialStore';
import { useMidiStore } from '../store/useMidiStore';
import { useTempoStore } from '../store/useTempoStore';
import './SettingsView.css';

const MODE_LABELS: Record<DmxOutputMode, string> = {
  baudRateBreak: 'Baud-rate BREAK (standard FTDI cable)',
  enttecOpen:    'Enttec Open DMX USB',
  enttecPro:     'Enttec DMX USB Pro',
  eurolite:      'Eurolite USB-DMX512 Pro / Cable / MK2',
};

interface TestedDmxDevice {
  id: string;
  name: string;
  manufacturer: string;
  mode: DmxOutputMode;
  description: string;
}

const TESTED_DEVICES: TestedDmxDevice[] = [
  {
    id: 'orbit-bridge',
    name: 'OrbitBridgeDeck',
    manufacturer: 'Akashic Trance Machines',
    mode: 'enttecPro',
    description: 'RP2350-based pro interface with dedicated hardware timing.',
  },
  {
    id: 'enttec-pro',
    name: 'DMX USB Pro / Pro Mk2',
    manufacturer: 'Enttec',
    mode: 'enttecPro',
    description: 'Industry-standard message-framed hardware DMX interface.',
  },
  {
    id: 'enttec-open',
    name: 'Open DMX USB',
    manufacturer: 'Enttec',
    mode: 'enttecOpen',
    description: 'Hardware BREAK generated by the adapter. Requires stable host timing.',
  },
  {
    id: 'eurolite-pro',
    name: 'USB-DMX512 Pro / Pro Cable / Pro MK2',
    manufacturer: 'Eurolite',
    mode: 'eurolite',
    description: 'High-speed 250,000 baud interface with custom framing.',
  },
  {
    id: 'dmxking-ultra',
    name: 'ultraDMX Pro / Micro',
    manufacturer: 'DMXKing',
    mode: 'enttecPro',
    description: 'Fully compatible Enttec Pro clone with robust performance.',
  },
  {
    id: 'generic-ftdi',
    name: 'Generic FTDI USB-DMX Cable',
    manufacturer: 'Generic FTDI',
    mode: 'baudRateBreak',
    description: 'Software-driven BREAK via baud-rate switching. Works on any FTDI-based cable.',
  },
  {
    id: 'generic-ch340',
    name: 'Generic CH340 / CP210x Cable',
    manufacturer: 'Generic',
    mode: 'baudRateBreak',
    description: 'Entry-level USB-to-serial chips. Best compatibility but software-timed.',
  },
];

export default function SettingsView() {
  const [ports, setPorts] = useState<SerialPortInfo[]>([]);
  const [scanning, setScanning] = useState(false);
  const [selectedPort, setSelectedPort] = useState<string>('');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // Read connection state from the global store (kept alive by App.tsx)
  const status = useSerialStore((s) => s.status);
  const connectedPort = useSerialStore((s) => s.connectedPort);
  const setConnectedPort = useSerialStore((s) => s.setConnectedPort);
  const outputMode = useSerialStore((s) => s.outputMode);
  const storeSetOutputMode = useSerialStore((s) => s.setOutputMode);

  const isConnected    = status === 'connected';
  const isConnecting   = status === 'connecting' || status === 'reconnecting';
  const isReconnecting = status === 'reconnecting';

  // Persistence of selected product dropdown
  const [selectedDeviceId, setSelectedDeviceId] = useState<string>(() => {
    return localStorage.getItem('orbitdmx-selected-device') ?? 'orbit-bridge';
  });

  // Pre-select the active port when navigating back to Settings
  useEffect(() => {
    if (connectedPort) setSelectedPort(connectedPort);
  }, [connectedPort]);

  // Load current engine output mode and sync with selected product on mount
  useEffect(() => {
    if (typeof window.dmx === 'undefined') return;
    window.dmx.getOutputMode().then((res) => {
      if (res.success && res.data) {
        const currentMode = res.data.mode as DmxOutputMode;
        
        // See if there's a stored device, and if its mode matches the engine's current mode
        const storedId = localStorage.getItem('orbitdmx-selected-device');
        const storedDev = TESTED_DEVICES.find((d) => d.id === storedId);
        
        if (storedDev && storedDev.mode === currentMode) {
          setSelectedDeviceId(storedDev.id);
          storeSetOutputMode(currentMode, false);
        } else {
          // Otherwise find the first tested device that matches the active mode
          const matchingDev = TESTED_DEVICES.find((d) => d.mode === currentMode);
          if (matchingDev) {
            setSelectedDeviceId(matchingDev.id);
            localStorage.setItem('orbitdmx-selected-device', matchingDev.id);
          }
          storeSetOutputMode(currentMode, false);
        }
      }
    });
  }, []);

  const handleDeviceChange = async (deviceId: string) => {
    setSelectedDeviceId(deviceId);
    localStorage.setItem('orbitdmx-selected-device', deviceId);
    
    const dev = TESTED_DEVICES.find((d) => d.id === deviceId);
    if (dev) {
      storeSetOutputMode(dev.mode, false);
      if (typeof window.dmx !== 'undefined') {
        await window.dmx.setOutputMode(dev.mode);
      }
    }
  };

  const scanPorts = useCallback(async () => {
    setScanning(true);
    setErrorMsg(null);
    try {
      if (typeof window.dmx === 'undefined') {
        // Dev preview — simulate a port list
        await new Promise((r) => setTimeout(r, 600));
        setPorts([{ path: '/dev/cu.usbserial-AV0LC2WD', manufacturer: 'FTDI', serialNumber: 'AV0LC2WD' }]);
        return;
      }
      const result = await window.dmx.listPorts();
      if (result.success) {
        setPorts((result.data as SerialPortInfo[]) ?? []);
      } else {
        setErrorMsg(result.error ?? 'Failed to list ports');
      }
    } finally {
      setScanning(false);
    }
  }, []);

  // Auto-scan on mount
  useEffect(() => { scanPorts(); }, []);

  const handleConnect = async () => {
    if (!selectedPort) return;
    setErrorMsg(null);
    try {
      if (typeof window.dmx === 'undefined') {
        // Dev preview
        useSerialStore.getState().setStatus('connecting');
        await new Promise((r) => setTimeout(r, 800));
        useSerialStore.getState().setStatus('connected');
        setConnectedPort(selectedPort);
        return;
      }
      const result = await window.dmx.connect(selectedPort);
      if (!result.success) {
        setErrorMsg(result.error ?? 'Connection failed');
      } else {
        setConnectedPort(selectedPort);
      }
    } catch (e) {
      setErrorMsg(String(e));
    }
  };

  const handleDisconnect = async () => {
    setErrorMsg(null);
    try {
      if (typeof window.dmx !== 'undefined') {
        await window.dmx.disconnect();
      }
      setConnectedPort(null);
    } catch (e) {
      setErrorMsg(String(e));
    }
  };

  const activeDevice = TESTED_DEVICES.find((d) => d.id === selectedDeviceId) ?? TESTED_DEVICES[0];

  return (
    <div className="settings-view">
      <div className="settings-header">
        <h1>Settings</h1>
      </div>

      <div className="settings-content">

        {/* DMX Adapter section */}
        <section className="settings-section" id="section-dmx-adapter">
          <div className="settings-section-header">
            <h2>DMX Adapter</h2>
            <p className="settings-section-desc">
              Connect your USB-to-DMX interface. Select your port and the specific tested hardware product below.
            </p>
          </div>

          {/* Connection status badge */}
          <div className={`connection-status status-${isReconnecting ? 'connecting' : status}`}>
            <span className="status-dot" />
            <span className="status-label">
              {status === 'connected'     && `Connected — ${connectedPort ?? selectedPort} (${activeDevice.name})`}
              {status === 'connecting'    && 'Connecting…'}
              {status === 'reconnecting'  && `Reconnecting… — ${connectedPort ?? selectedPort}`}
              {status === 'disconnected'  && 'No adapter connected'}
              {status === 'error'         && 'Connection error'}
            </span>
          </div>

          <div className="dmx-connector-grid">
            <div className="connector-field">
              <label htmlFor="select-serial-port" className="connector-label">Serial Port</label>
              <div className="port-selector-row">
                <div className="port-select-wrap">
                  <select
                    id="select-serial-port"
                    className="form-select"
                    value={selectedPort}
                    onChange={(e) => setSelectedPort(e.target.value)}
                    disabled={isConnected || isConnecting}
                  >
                    <option value="">— Select a port —</option>
                    {ports.map((p) => (
                      <option key={p.path} value={p.path}>
                        {p.path}
                        {p.manufacturer ? ` · ${p.manufacturer}` : ''}
                      </option>
                    ))}
                  </select>
                </div>

                <button
                  id="btn-scan-ports"
                  className="btn-icon"
                  title="Refresh port list"
                  onClick={scanPorts}
                  disabled={scanning || isConnecting}
                >
                  <span className={scanning ? 'spin' : ''}>↺</span>
                </button>
              </div>
            </div>

            <div className="connector-field">
              <label htmlFor="select-dmx-device" className="connector-label">USB-to-DMX Product</label>
              <div className="port-select-wrap">
                <select
                  id="select-dmx-device"
                  className="form-select"
                  value={selectedDeviceId}
                  onChange={(e) => handleDeviceChange(e.target.value)}
                  disabled={isConnected || isConnecting}
                >
                  {TESTED_DEVICES.map((d) => (
                    <option key={d.id} value={d.id}>
                      {d.manufacturer} — {d.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>
          </div>

          {/* Device details panel */}
          <div className="device-details-card">
            <p className="device-details-desc">{activeDevice.description}</p>
            <div className="device-details-meta">
              <span className="meta-protocol">Protocol: <strong>{MODE_LABELS[activeDevice.mode]}</strong></span>
            </div>
          </div>

          {/* Action button */}
          <div className="connector-actions">
            {!isConnected && !isReconnecting ? (
              <button
                id="btn-connect"
                className="btn-primary connect-full-width"
                onClick={handleConnect}
                disabled={!selectedPort || isConnecting}
              >
                {isConnecting ? 'Connecting…' : 'Connect DMX Adapter'}
              </button>
            ) : (
              <button
                id="btn-disconnect"
                className="btn-danger disconnect-full-width"
                onClick={handleDisconnect}
                disabled={isReconnecting}
                title={isReconnecting ? 'Auto-reconnecting…' : undefined}
              >
                {isReconnecting ? 'Reconnecting…' : 'Disconnect'}
              </button>
            )}
          </div>

          {/* Error */}
          {errorMsg && (
            <div className="settings-error" style={{ marginTop: 8 }}>
              ⚠ {errorMsg}
            </div>
          )}
        </section>


        {/* MIDI Devices section */}
        <section className="settings-section" id="section-midi">
          <div className="settings-section-header">
            <h2>MIDI Devices</h2>
            <p className="settings-section-desc">
              Select a MIDI input device for Controls and Tempo Sync.
              Only one device is active at a time.
            </p>
          </div>

          <MidiDeviceSelector />
        </section>

        {/* MIDI Tempo Sync section */}
        <section className="settings-section" id="section-midi-tempo">
          <div className="settings-section-header">
            <h2>MIDI Tempo Sync</h2>
            <p className="settings-section-desc">
              Lock the global BPM to an incoming MIDI Clock signal (System Real-Time, 0xF8).
            </p>
          </div>
          <MidiTempoSyncPanel />
        </section>

        {/* Show file section */}
        <section className="settings-section" id="section-show-file">
          <div className="settings-section-header">
            <h2>Show File</h2>
            <p className="settings-section-desc">
              Export or import a portable <code>.orbitshow</code> bundle containing all fixtures, scenes, playlists, controls, and rig definitions.
            </p>
          </div>
          <div className="port-selector-row">
            <button className="btn-primary" onClick={() => window.dispatchEvent(new CustomEvent('menu:export-show'))}>
              📦 Export Show…
            </button>
            <button className="btn-primary" onClick={() => window.dispatchEvent(new CustomEvent('menu:import-show'))}>
              📂 Import Show…
            </button>
          </div>
        </section>

        {/* About section */}
        <section className="settings-section" id="section-about">
          <div className="settings-section-header">
            <h2>About</h2>
          </div>
          <div className="about-item">
            <span className="about-label">Software</span>
            <span className="about-value">OrbitDMX Controller</span>
          </div>
          <div className="about-row">
            <span className="about-label">Version</span>
            <span className="about-value mono">v{__APP_VERSION__}</span>
          </div>
          <div className="about-row">
            <span className="about-label">Protocol</span>
            <span className="about-value">{MODE_LABELS[outputMode]}</span>
          </div>
        </section>

      </div>
    </div>
  );
}

/* ── MIDI Device Selector (≡ DMX adapter section UX) ────────────────────────── */

function MidiDeviceSelector() {
  const devices           = useMidiStore((s) => s.devices);
  const isListening       = useMidiStore((s) => s.isListening);
  const connectedDeviceId = useMidiStore((s) => s.connectedDeviceId);
  const lastMessage       = useMidiStore((s) => s.lastMessage);
  const { connectDevice, disconnectDevice } = useMidiStore.getState();

  const [selectedId, setSelectedId] = useState<string>(connectedDeviceId ?? '');

  useEffect(() => {
    if (connectedDeviceId && selectedId !== connectedDeviceId) {
      setSelectedId(connectedDeviceId);
    }
  }, [connectedDeviceId]);

  const connectedDevice     = devices.find((d) => d.id === connectedDeviceId);
  const connectedButMissing = connectedDeviceId && !connectedDevice;
  const isConnected         = !!connectedDevice;

  let statusClass = 'status-disconnected';
  let statusLabel = 'Not connected';
  if (!isListening) {
    statusClass = 'status-error';
    statusLabel = 'Web MIDI not available in this environment';
  } else if (connectedDevice) {
    statusClass = 'status-connected';
    statusLabel = `Connected — ${connectedDevice.name}`;
  } else if (connectedButMissing) {
    statusClass = 'status-error';
    statusLabel = 'Device disconnected — waiting for reconnect';
  }

  return (
    <div>
      {/* Status badge */}
      <div className={`connection-status ${statusClass}`}>
        <span className="status-dot" />
        <span className="status-label">{statusLabel}</span>
      </div>

      {/* Device selector */}
      <div className="dmx-connector-grid" style={{ marginTop: 12 }}>
        <div className="connector-field">
          <label htmlFor="select-midi-device" className="connector-label">MIDI Input Device</label>
          <div className="port-select-wrap">
            <select
              id="select-midi-device"
              className="form-select"
              value={selectedId}
              onChange={(e) => setSelectedId(e.target.value)}
              disabled={isConnected || !isListening}
            >
              <option value="">— Select a device —</option>
              {devices.map((d) => (
                <option key={d.id} value={d.id}>{d.name}</option>
              ))}
            </select>
          </div>
          {devices.length === 0 && isListening && (
            <p className="settings-section-desc" style={{ marginTop: 6 }}>
              No MIDI input devices detected. Connect a MIDI controller via USB.
            </p>
          )}
        </div>
      </div>

      {/* Action button */}
      <div className="connector-actions">
        {!isConnected ? (
          <button
            id="btn-midi-connect"
            className="btn-primary connect-full-width"
            onClick={() => { if (selectedId) connectDevice(selectedId); }}
            disabled={!selectedId || !isListening}
          >
            Connect MIDI Device
          </button>
        ) : (
          <button
            id="btn-midi-disconnect"
            className="btn-danger disconnect-full-width"
            onClick={() => { disconnectDevice(); setSelectedId(''); }}
          >
            Disconnect
          </button>
        )}
      </div>

      {/* Last MIDI message monitor */}
      {lastMessage && connectedDeviceId && (
        <div className="device-details-card" style={{ marginTop: 8 }}>
          <p className="device-details-desc" style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>
            Last: CH {lastMessage.channel} / CC {lastMessage.cc} = {lastMessage.value}
          </p>
        </div>
      )}
    </div>
  );
}

/* ── MIDI Tempo Sync Panel ──────────────────────────────────────────────────── */

const PPQN_OPTIONS: { value: number; label: string; desc: string }[] = [
  { value: 24, label: '24 — Standard (1/4 note)', desc: '24 clock ticks = 1 beat (quarter note). Standard MIDI.' },
  { value: 12, label: '12 — Half (1/8 note)',     desc: '12 clock ticks = 1 beat. Each beat is an eighth note.' },
  { value: 6,  label: '6 — Quarter (1/16 note)',  desc: '6 clock ticks = 1 beat. Each beat is a sixteenth note.' },
  { value: 3,  label: '3 — Eighth (1/32 note)',   desc: '3 clock ticks = 1 beat. Each beat is a 32nd note.' },
  { value: 1,  label: '1 — Raw tick',              desc: 'Every clock tick counts as a beat.' },
];

function MidiTempoSyncPanel() {
  const midiSyncEnabled = useTempoStore((s) => s.midiSyncEnabled);
  const midiClockActive = useTempoStore((s) => s.midiClockActive);
  const midiPpqn        = useTempoStore((s) => s.midiPpqn);
  const bpm             = useTempoStore((s) => s.bpm);
  const { setMidiSyncEnabled, setMidiPpqn } = useTempoStore.getState();

  const selectedOption = PPQN_OPTIONS.find((o) => o.value === midiPpqn) ?? PPQN_OPTIONS[0];

  return (
    <div>
      {/* Enable toggle */}
      <div className="settings-toggle-row">
        <label className="settings-toggle-label" htmlFor="toggle-midi-sync">
          Enable MIDI Clock Sync
        </label>
        <button
          id="toggle-midi-sync"
          className={`settings-toggle-btn ${midiSyncEnabled ? 'active' : ''}`}
          onClick={() => setMidiSyncEnabled(!midiSyncEnabled)}
          role="switch"
          aria-checked={midiSyncEnabled}
        >
          <span className="settings-toggle-thumb" />
        </button>
      </div>

      {midiSyncEnabled && (
        midiClockActive ? (
          /* Clock signal present */
          <div className="connection-status status-connected" style={{ marginBottom: 12 }}>
            <span className="status-dot" />
            <span className="status-label" style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>
              Sync active — {bpm.toFixed(1)} BPM
            </span>
          </div>
        ) : (
          /* Sync enabled but no clock arriving */
          <div className="connection-status status-error" style={{ marginBottom: 12 }}>
            <span className="status-dot" />
            <span className="status-label" style={{ fontSize: 11 }}>
              No clock signal received — using global BPM
            </span>
          </div>
        )
      )}

      {/* PPQN selector */}
      <div className="port-selector-row" style={{ alignItems: 'flex-start', flexDirection: 'column', gap: 8 }}>
        <label className="settings-toggle-label" htmlFor="select-ppqn">
          Pulses per Quarter Note (PPQN)
        </label>
        <div className="port-select-wrap">
          <select
            id="select-ppqn"
            className="form-select"
            value={midiPpqn}
            onChange={(e) => setMidiPpqn(Number(e.target.value))}
            disabled={!midiSyncEnabled}
          >
            {PPQN_OPTIONS.map((o) => (
              <option key={o.value} value={o.value}>{o.label}</option>
            ))}
          </select>
        </div>
        <p className="settings-section-desc" style={{ marginTop: 0 }}>
          {selectedOption.desc}
        </p>
      </div>
    </div>
  );
}

